/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LET = 7;
  /** RegularExpression Id. */
  int PRINT = 8;
  /** RegularExpression Id. */
  int IN = 9;
  /** RegularExpression Id. */
  int END = 10;
  /** RegularExpression Id. */
  int FUN = 11;
  /** RegularExpression Id. */
  int R_ARROW = 12;
  /** RegularExpression Id. */
  int COMMA = 13;
  /** RegularExpression Id. */
  int D_EQ = 14;
  /** RegularExpression Id. */
  int EQ = 15;
  /** RegularExpression Id. */
  int ATTRIB = 16;
  /** RegularExpression Id. */
  int NEW = 17;
  /** RegularExpression Id. */
  int DERREF = 18;
  /** RegularExpression Id. */
  int N_EQ = 19;
  /** RegularExpression Id. */
  int BOOL_TYPE = 20;
  /** RegularExpression Id. */
  int INT_TYPE = 21;
  /** RegularExpression Id. */
  int REF_TYPE = 22;
  /** RegularExpression Id. */
  int Bool = 23;
  /** RegularExpression Id. */
  int IF = 24;
  /** RegularExpression Id. */
  int THEN = 25;
  /** RegularExpression Id. */
  int ELSE = 26;
  /** RegularExpression Id. */
  int WHILE = 27;
  /** RegularExpression Id. */
  int DO = 28;
  /** RegularExpression Id. */
  int FOR = 29;
  /** RegularExpression Id. */
  int NOT = 30;
  /** RegularExpression Id. */
  int AND = 31;
  /** RegularExpression Id. */
  int OR = 32;
  /** RegularExpression Id. */
  int GREATER_EQ = 33;
  /** RegularExpression Id. */
  int LOWER_EQ = 34;
  /** RegularExpression Id. */
  int LOWER = 35;
  /** RegularExpression Id. */
  int GREATER = 36;
  /** RegularExpression Id. */
  int D_DOTS = 37;
  /** RegularExpression Id. */
  int ID = 38;
  /** RegularExpression Id. */
  int Num = 39;
  /** RegularExpression Id. */
  int PLUS = 40;
  /** RegularExpression Id. */
  int MINUS = 41;
  /** RegularExpression Id. */
  int TIMES = 42;
  /** RegularExpression Id. */
  int DIV = 43;
  /** RegularExpression Id. */
  int MOD = 44;
  /** RegularExpression Id. */
  int LPAR = 45;
  /** RegularExpression Id. */
  int RPAR = 46;
  /** RegularExpression Id. */
  int SEMI_COLON = 47;
  /** RegularExpression Id. */
  int EL = 48;
  /** RegularExpression Id. */
  int STRING = 49;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<token of kind 6>",
    "\"let\"",
    "\"println\"",
    "\"in\"",
    "\"end\"",
    "\"fun\"",
    "<R_ARROW>",
    "\",\"",
    "\"==\"",
    "\"=\"",
    "\":=\"",
    "\"new\"",
    "\"!\"",
    "\"!=\"",
    "<BOOL_TYPE>",
    "<INT_TYPE>",
    "<REF_TYPE>",
    "<Bool>",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"for\"",
    "\"~\"",
    "\"&&\"",
    "\"||\"",
    "\">=\"",
    "\"<=\"",
    "\"<\"",
    "\">\"",
    "\":\"",
    "<ID>",
    "<Num>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\";;\"",
    "<STRING>",
  };

}
