/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LET = 7;
  /** RegularExpression Id. */
  int IN = 8;
  /** RegularExpression Id. */
  int END = 9;
  /** RegularExpression Id. */
  int FUN = 10;
  /** RegularExpression Id. */
  int R_ARROW = 11;
  /** RegularExpression Id. */
  int COMMA = 12;
  /** RegularExpression Id. */
  int D_EQ = 13;
  /** RegularExpression Id. */
  int EQ = 14;
  /** RegularExpression Id. */
  int ATTRIB = 15;
  /** RegularExpression Id. */
  int NEW = 16;
  /** RegularExpression Id. */
  int DERREF = 17;
  /** RegularExpression Id. */
  int N_EQ = 18;
  /** RegularExpression Id. */
  int BOOL_TYPE = 19;
  /** RegularExpression Id. */
  int INT_TYPE = 20;
  /** RegularExpression Id. */
  int REF_TYPE = 21;
  /** RegularExpression Id. */
  int Bool = 22;
  /** RegularExpression Id. */
  int IF = 23;
  /** RegularExpression Id. */
  int THEN = 24;
  /** RegularExpression Id. */
  int ELSE = 25;
  /** RegularExpression Id. */
  int WHILE = 26;
  /** RegularExpression Id. */
  int DO = 27;
  /** RegularExpression Id. */
  int FOR = 28;
  /** RegularExpression Id. */
  int NOT = 29;
  /** RegularExpression Id. */
  int AND = 30;
  /** RegularExpression Id. */
  int OR = 31;
  /** RegularExpression Id. */
  int GREATER_EQ = 32;
  /** RegularExpression Id. */
  int LOWER_EQ = 33;
  /** RegularExpression Id. */
  int LOWER = 34;
  /** RegularExpression Id. */
  int GREATER = 35;
  /** RegularExpression Id. */
  int D_DOTS = 36;
  /** RegularExpression Id. */
  int ID = 37;
  /** RegularExpression Id. */
  int Num = 38;
  /** RegularExpression Id. */
  int PLUS = 39;
  /** RegularExpression Id. */
  int MINUS = 40;
  /** RegularExpression Id. */
  int TIMES = 41;
  /** RegularExpression Id. */
  int DIV = 42;
  /** RegularExpression Id. */
  int MOD = 43;
  /** RegularExpression Id. */
  int LPAR = 44;
  /** RegularExpression Id. */
  int RPAR = 45;
  /** RegularExpression Id. */
  int SEMI_COLON = 46;
  /** RegularExpression Id. */
  int EL = 47;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<token of kind 6>",
    "\"let\"",
    "\"in\"",
    "\"end\"",
    "\"fun\"",
    "<R_ARROW>",
    "\",\"",
    "\"==\"",
    "\"=\"",
    "\":=\"",
    "\"new\"",
    "\"!\"",
    "\"!=\"",
    "<BOOL_TYPE>",
    "<INT_TYPE>",
    "<REF_TYPE>",
    "<Bool>",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"for\"",
    "\"~\"",
    "\"&&\"",
    "\"||\"",
    "\">=\"",
    "\"<=\"",
    "\"<\"",
    "\">\"",
    "\":\"",
    "<ID>",
    "<Num>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\";;\"",
  };

}
